# Uncomment the next line to define a global platform for your project
 platform :ios, '7.0'

target 'RecordCrashLogTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for RecordCrashLogTest
  pod 'AvoidCrash', '~> 1.6.2'
  pod 'Bugly'
  pod 'KSCrash', '~> 1.15.0'
end
